### ISSUE TITLE
Descripción de requisitos funcionales

### ISSUE THREAD

**Issue by Pj-9** [Jorgesi27/iw2023-2024-KembaMobile#1]

**Comment by Jorgesi27** [comment]
### **Requisitos funcionales**


**Front-Office**

Asignar Servicio: el sistema asigna al cliente, el servicio que contrate. Los servicios son: fibra, móvil, fijo o combinados.

Modificar Servicio: el sistema modifica los servicios contratados por un cliente.

Mostrar Volumen: el sistema muestra los datos del volumen mensual del cliente. Estos datos son: desglose de llamadas, sms, consumo de datos 5G diario y el roaming.

Mostrar Factura: el sistema muestra al cliente su factura y permite que se descargue en formato PDF.

Activar Roaming: el sistema activa o desactiva la opción el roaming al cliente.

Modificar Líneas: el sistema modifica los datos entre las líneas del cliente.

Bloquear Números: el sistema bloquea números especiales al cliente.

Crear Consulta: el sistema canalizará las consultas o reclamaciones (online u offline) realizadas por los clientes para que sean atendidas por empleados de la empresa.


**Back-Office**

Gestión de Característica: el sistema permite al departamento de ventas y marketing crear, modificar, eliminar, buscar y mostrar las características de los servicios prestados.

Gestión de Tarifa: el sistema permite al departamento de ventas y marketing crear, modificar, eliminar, buscar y mostrar las tarifas de los servicios prestados.

Gestión de Contrato: el sistema permite al departamento de atención al cliente crear, modificar, eliminar, buscar y mostrar los contratos de los clientes.

Mostrar Consulta: el sistema permite al departamento de atención al cliente mostrar las consultas o reclamaciones  de los clientes para atenderlas.
Crear Factura: el sistema permite al departamento de finanzas generar las facturas de los clientes.

Envíar Factura:el sistema permite al departamento de finanzas envíar las facturas de los clientes.
