### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by Pj-9** [Jorgesi27/iw2023-2024-KembaMobile#3]

**Comment by Jorgesi27** [comment]
![CUFrontOffice](https://github.com/Jorgesi27/iw2023-2024-KembaMobile/assets/147847682/5e20dc84-640a-4a7c-b138-e6bd6a8df632)
![CUFrontOffice](https://github.com/Jorgesi27/iw2023-2024-KembaMobile/assets/147847682/594ac7b6-5746-4f2c-a680-12eddf55e2fa)

**Comment by Jorgesi27** [comment]
![CUBackOffice](https://github.com/Jorgesi27/iw2023-2024-KembaMobile/assets/147847682/8b7bce3a-cd10-463d-a6a8-1018b569bebb)
